// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCv8obQNlEyXFJRiB5UvGwcFTfECkV2iT0',
    appId: '1:643406650007:web:e08d1ff845b8384bab67d2',
    messagingSenderId: '643406650007',
    projectId: 'ledgrr-b51bd',
    authDomain: 'ledgrr-b51bd.firebaseapp.com',
    storageBucket: 'ledgrr-b51bd.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtnPdn_Vy55akG9lz6OQiFvfZxCGHyIdE',
    appId: '1:643406650007:android:4df39d85a5352628ab67d2',
    messagingSenderId: '643406650007',
    projectId: 'ledgrr-b51bd',
    storageBucket: 'ledgrr-b51bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANou4su0mDE3k1Vp9PE6vf7BsyuOVqlUs',
    appId: '1:643406650007:ios:b4524b32bad90bb7ab67d2',
    messagingSenderId: '643406650007',
    projectId: 'ledgrr-b51bd',
    storageBucket: 'ledgrr-b51bd.appspot.com',
    iosClientId: '643406650007-pj2u63ia4m235ge4h60h6u1dadfn2vkh.apps.googleusercontent.com',
    iosBundleId: 'com.example.ledgrr',
  );
}
